const eng = {
  ADDTOCART: "Add to Cart",
  HOME: "Home",
  STORE: "Store",
  STORENAME: "Rushop",
  SEARCHPRODUCTSPLACEHOLDER: "Search products...",
  PAGE: "Page",
  OF: "of",
  FILTERBYCATEGORY: "Filter by category",
  LOADING: "Loading...",
  CART_EMPTY: "Your cart is empty :(",
  VIEW_CART: "View Cart",
  CARTLOADING: "Loading Cart...",
  YOURCART: "Your Cart",
  CART_TOTAL: "Cart Total:",
  DIVIDERDOT: "•",
  PERCENT: "%",
  GO_TO_CHECKOUT: "Go to Checkout",
  REMOVE_FROM_CART: "Remove from Cart",
  MINUS: "-",
  PLUS: "+",
  X: "x",
  WELCOMETO: "Welcome to ",
  EXMARK: "!",
  HERODESCRIPTION:
    "Discover amazing products from an endopoint provided by Sikuro.",
  DISCOVERMORETEXT: "Discover amazing products and deals",
  DISCOVERMORE: "Discover More",
  PRODUCTNOTFOUND:
    "The product you're looking for doesn't exist... but we have a lot more to offer!",
  SHOPNOW: "Shop Now",
  RATING: "Rating:",
  REVIEWS: "Reviews:",
  DESCRIPTION: "Description:",
  STOCK: "Stock:",
  WEIGHT: "Weight:",
  DIMENSIONS: "Dimensions:",
  WARRANTYINFORMATION: "Warranty Information:",
  SHIPPINGINFORMATION: "Shipping Information:",
  SHIPPING: "Shipping:",
  WARRANTY: "Warranty:",
  MINIMUMORDER: "Minimum Order Quantity:",
  AVAILABILITY: "Availability:",
  RETURNPOLICY: "Return Policy:",
  MINIMUMORDERQUANTITY: "Minimum Order Quantity:",
  STAR: "⭐",
  G: "g",
  CM: "cm",
}

export default eng
